name: Build distribution

on: [push]

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/testpythonpackagelibialany
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python -m pip install -U build

      - name: Build a binary wheel and a source tarball
        run: python -m build

      - name: Upload release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
