name: Build distribution

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: python -m pip install -U build

      - name: Build package
        run: python -m build
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.pypi_password }}
    steps:
      - name: Publish package to PyPI
        if:  env.TOKEN != '' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: elibialany 
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.pypi_password }}