name: Build distribution

on: [push, pull_request]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python 3.11.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.9

      - name: Install build dependencies
        run: python3 -m pip install --upgrade build && python3 -m build

      - name: Publish package to PyPI
        if: github.repository == 'libialany/testPythonPackage' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: elibialany 
          repository-url: https://test.pypi.org/simple/
          password: ${{ secrets.pypi_password }}